- name: 'Configure /etc/hosts for all LAB hosts'
  blockinfile:
    path: /etc/hosts
    marker: "# LAB HOSTS"
    block: |
      172.16.0.2  k8s-master1
      172.16.0.3  k8s-master2
      172.16.0.4  k8s-master3
      172.16.0.10 k8s-lb
      172.16.0.20 k8s-worker1
      172.16.0.21 k8s-worker2
      172.16.0.22 k8s-worker3
      

- name: 'Delete unnecessary entries from /etc/hosts file'
  lineinfile:
    path: /etc/hosts
    state: absent
    regexp: '^127.0.1.1 k8s'

