---
- name: 'Replace generic configuration append extra config'
  copy:
    src: /opt/gitlab/etc/gitlab.rb.template
    dest: /etc/gitlab/gitlab.rb
    remote_src: yes

- name: 'Set external_url for gitlab'
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "external_url 'GENERATED_EXTERNAL_URL'"
    line: "external_url 'https://cicd'"

#- name: 'Set registry_external_url for gitlab'
#  lineinfile:
#    path: /etc/gitlab/gitlab.rb
#    regexp: "registry_external_url 'https://registry.example.com'"
#    line: "registry_external_url 'https://cicd:8443'"

- name: 'Reconfigure gitlab according to new config'
  shell: /opt/gitlab/bin/gitlab-ctl reconfigure
  args:
    warn: no
  register: status

- debug: msg="{{ status.stdout }}"
- debug: msg="{{ status.stderr }}"

- name: 'Check gitlab processes'
  shell: /opt/gitlab/bin/gitlab-ctl status
  args:
    warn: no
  register: status

- debug: msg="{{ status.stdout }}"
- debug: msg="{{ status.stderr }}"


- name: 'SSL certificate less expired'
  copy:
    src: /opt/gitlab/etc/gitlab.rb.template
    dest: /etc/gitlab/gitlab.rb
    remote_src: yes

- name: 'SSL certificate less expired'
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'files/ssl/cicd.key', dest: '/etc/gitlab/ssl/cicd.key' }
    - { src: 'files/ssl/cicd.crt', dest: '/etc/gitlab/ssl/cicd.crt' }

- name: 'Restart Gitlab services'
  shell: /opt/gitlab/bin/gitlab-ctl restart
  args:
    warn: no
  register: status
